runtime: python39

handlers:
- url: /_next/static
  static_dir: out/_next/static
  secure: always

- url: /(.*)
  static_files: out/\1
  upload: out/(.*)
  secure: always

- url: /
  static_files: out/index.html
  upload: out/index.html
  secure: always